# cimo -
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

# cimo +
uebusaito:
    resource: "@UebusaitoBundle/Resources/config/routing.yml"
    prefix: /
    requirements:
        locale: "[a-z]{2}"
        urlCurrentPageId: "\d+"
        urlExtra: ".*"