ReinventSoftware\UebusaitoBundle\Form\Model\PasswordModel:
    properties:
        old:
            - NotBlank:
                groups: [profile_password]
            - Regex:
                groups: [profile_password]
                htmlPattern: false
                pattern: /^.{8,20}$/
                message: entity.user.password
        new:
            - NotBlank:
                groups: [profile_password]
            - Regex:
                groups: [profile_password]
                htmlPattern: false
                pattern: /^.{8,20}$/
                message: entity.user.password
        newConfirm:
            - NotBlank:
                groups: [profile_password]
            - Regex:
                groups: [profile_password]
                htmlPattern: false
                pattern: /^.{8,20}$/
                message: entity.user.password

ReinventSoftware\UebusaitoBundle\Form\Model\ChangePasswordModel:
    properties:
        password:
            - NotBlank:
                groups: [change_password]
            - Regex:
                groups: [change_password]
                htmlPattern: false
                pattern: /^{8,20}$/
                message: entity.user.password
        passwordConfirm:
            - NotBlank:
                groups: [change_password]
            - Regex:
                groups: [change_password]
                htmlPattern: false
                pattern: /^{8,20}$/
                message: entity.user.password

ReinventSoftware\UebusaitoBundle\Form\Model\RecoverPasswordModel:
    properties:
        email:
            - NotBlank:
                groups: [recover_password]
            - Regex:
                groups: [recover_password]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/

ReinventSoftware\UebusaitoBundle\Form\Model\CreditsModel:
    properties:
        credits:
            - NotBlank:
                groups: [profile_credits]
            - Regex:
                groups: [profile_credits]
                htmlPattern: false
                pattern: /^[0-9]+$/

ReinventSoftware\UebusaitoBundle\Form\Model\LanguageModel:
    properties:
        codeText:
            - NotBlank:
                groups: [language_text]
            - Regex:
                groups: [language_text]
                htmlPattern: false
                pattern: /^[a-z]{2}$/
        codePage:
            - NotBlank:
                groups: [language_code]
            - Regex:
                groups: [language_code]
                htmlPattern: false
                pattern: /^[a-z]{2}$/

ReinventSoftware\UebusaitoBundle\Form\Model\SearchModel:
    properties:
        words:
            - NotBlank:
                groups: [search_module]
            - Regex:
                groups: [search_module]
                htmlPattern: false
                pattern: /^.{1,150}$/

ReinventSoftware\UebusaitoBundle\Form\Model\PaymentsUserSelectionModel:
    properties:
        userId:
            - Regex:
                groups: [payments_user_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

ReinventSoftware\UebusaitoBundle\Form\Model\PaymentsSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [payments_selection]
            - Regex:
                groups: [payments_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

ReinventSoftware\UebusaitoBundle\Form\Model\PagesSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [pages_selection]
            - Regex:
                groups: [pages_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

ReinventSoftware\UebusaitoBundle\Form\Model\UsersSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [users_selection]
            - Regex:
                groups: [users_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

ReinventSoftware\UebusaitoBundle\Form\Model\ModulesSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [modules_selection]
            - Regex:
                groups: [modules_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

ReinventSoftware\UebusaitoBundle\Form\Model\RolesSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [roles_selection]
            - Regex:
                groups: [roles_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

ReinventSoftware\UebusaitoBundle\Entity\Page:
    properties:
        language:
            - NotBlank:
                groups: [page_profile]
            - Regex:
                groups: [page_profile]
                htmlPattern: false
                pattern: /^[a-z]+$/
        alias:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z_0-9]+$/
        parent:
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
        roleId:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        protected:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^1|^0/
        showInMenu:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^1|^0/
        menuName:
            - NotBlank:
                groups: [page_creation, page_profile]
        onlyLink:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^1|^0/
        link:
            - NotBlank:
                groups: [page_creation, page_profile]

ReinventSoftware\UebusaitoBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                groups: [registration, user_creation, user_profile]
            - Regex:
                groups: [registration, user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z0-9._]{4,20}$/
                message: entity.user.username
        roleId:
            - NotBlank:
                groups: [user_creation, user_profile]
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        name:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
        surname:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z']+$/
        email:
            - NotBlank:
                groups: [registration, profile, user_creation, user_profile]
            - Regex:
                groups: [registration, profile, user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/
        telephone:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
        born:
            - Date: ~
        gender:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]$/
        fiscalCode:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z][0-9]$/
        companyName:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
        vat:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
        website:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^(https?:\/\/)(www).([a-z0-9]+).([a-z]+)$/
        state:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
        city:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
        zip:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
        address:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z .0-9]+$/
        password:
            - NotBlank:
                groups: [registration, user_creation]
            - Regex:
                groups: [registration, user_creation]
                htmlPattern: false
                pattern: /^{8,20}$/
                message: entity.user.password
        passwordConfirm:
            - NotBlank:
                groups: [registration, user_creation]
            - Regex:
                groups: [registration, user_creation]
                htmlPattern: false
                pattern: /^{8,20}$/
                message: entity.user.password
        notLocked:
            - NotBlank:
                groups: [user_profile]
            - Regex:
                groups: [user_profile]
                htmlPattern: false
                pattern: /^1|^0/

ReinventSoftware\UebusaitoBundle\Entity\Module:
    properties:
        position:
            - NotBlank:
                groups: [module_creation]
            - Regex:
                groups: [module_creation, module_profile]
                htmlPattern: false
                pattern: /(header)|(left)|(center)|(right)/
        sort:
            - Regex:
                groups: [module_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        name:
            - NotBlank:
                groups: [module_creation, module_profile]
        fileName:
            - NotBlank:
                groups: [module_creation, module_profile]
            - Regex:
                groups: [module_creation, module_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z_.]+$/
        active:
            - NotBlank:
                groups: [module_profile]
            - Regex:
                groups: [module_profile]
                htmlPattern: false
                pattern: /^1|^0/

ReinventSoftware\UebusaitoBundle\Entity\Role:
    properties:
        level:
            - NotBlank:
                groups: [role_creation, role_profile]
            - Regex:
                groups: [role_creation, role_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z_]+$/

ReinventSoftware\UebusaitoBundle\Entity\Setting:
    properties:
        template:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[a-zA-Z_0-9]+$/
        templateColumn:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[1-4]+$/
        language:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[a-z]{2}$/
        emailAdmin:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/
        active:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^1|^0/
        roleId:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        https:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^1|^0/
        registrationUserConfirmAdmin:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^1|^0/
        loginAttemptTime:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[0-9]+$/
        loginAttemptCount:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[0-9]+$/
        captcha:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^1|^0/
        payPalSandbox:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^1|^0/
        payPalBusiness:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/
        payPalCurrencyCode:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[A-Z]{3}$/
        payPalCreditAmount:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[0-9]+(\.[0-9][0-9]?)?$/
        credits:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[0-9]+$/