error:
    path: /error
    defaults:
        _controller: FrameworkBundle:Template:template
        template: UebusaitoBundle::render/static/error.html.twig

index:
    path: /{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:Root:index, _locale: "%locale%", urlCurrentPageId: 2, urlExtra: ""}

# Language
language_text:
    path: /language_text/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:Language:text}

language_page:
    path: /language_page/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:Language:page}

# Search
search_words:
    path: /search_words/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:Search:words}
    
search_result:
    path: /search_result/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:Search:result}

# Registration
registration:
    path: /registration/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:Registration:index}

# Recover password
recover_password:
    path: /recover_password/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:RecoverPassword:index}

# Authentication
authentication_enter_check:
    path: /authentication_enter_check/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:Authentication:enterCheck}

authentication_exit_check:
    path: /authentication_exit_check/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:Authentication:exitCheck}

# Control panel - Profile
cp_profile:
    path: /cp_profile/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Profile:index}

cp_profile_password:
    path: /cp_profile_password/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Profile:password}

cp_profile_credits:
    path: /cp_profile_credits/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Profile:credits}

cp_profile_credits_payPal:
    path: /cp_profile_credits_payPal/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Profile:creditsPayPal}

# Control panel - Payments
cp_payments_user_selection:
    path: /cp_payments_user_selection/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Payment:userSelection}
    
cp_payments_selection:
    path: /cp_payments_selection/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Payment:selection}

cp_payment_profile:
    path: /cp_payment_profile/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Payment:profile}

cp_payment_deletion:
    path: /cp_payment_deletion/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Payment:deletion}

# Control panel - Pages
cp_page_creation:
    path: /cp_page_creation/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Page:creation}

cp_pages_selection:
    path: /cp_pages_selection/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Page:selection}

cp_page_profile:
    path: /cp_page_profile/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Page:profile}

cp_page_deletion:
    path: /cp_page_deletion/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Page:deletion}

# Control panel - Users
cp_user_creation:
    path: /cp_user_creation/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\User:creation}

cp_users_selection:
    path: /cp_users_selection/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\User:selection}

cp_user_profile:
    path: /cp_user_profile/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\User:profile}

cp_user_deletion:
    path: /cp_user_deletion/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\User:deletion}

# Control panel - Modules
cp_modules_drag:
    path: /cp_modules_drag/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Module:drag}

cp_module_creation:
    path: /cp_module_creation/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Module:creation}

cp_modules_selection:
    path: /cp_modules_selection/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Module:selection}

cp_module_profile:
    path: /cp_module_profile/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Module:profile}

cp_module_profile_sort:
    path: /cp_module_profile_sort/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Module:profileSort}

cp_module_deletion:
    path: /cp_module_deletion/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Module:deletion}

# Control panel - Roles
cp_role_creation:
    path: /cp_role_creation/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Role:creation}

cp_roles_selection:
    path: /cp_roles_selection/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Role:selection}

cp_role_profile:
    path: /cp_role_profile/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Role:profile}

cp_role_deletion:
    path: /cp_role_deletion/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Role:deletion}

# Control panel - Settings
cp_settings:
    path: /cp_settings/{_locale}/{urlCurrentPageId}/{urlExtra}
    defaults: {_controller: UebusaitoBundle:ControlPanel\Setting:modify}