ReinventSoftware\UebusaitoBundle\Form\Model\PasswordModel:
    properties:
        old:
            - NotBlank:
                groups: [profile_password]
        new:
            - NotBlank:
                groups: [profile_password]
        newConfirm:
            - NotBlank:
                groups: [profile_password]

ReinventSoftware\UebusaitoBundle\Form\Model\ChangePasswordModel:
    properties:
        password:
            - NotBlank:
                groups: [change_password]
        passwordConfirm:
            - NotBlank:
                groups: [change_password]

ReinventSoftware\UebusaitoBundle\Form\Model\RecoverPasswordModel:
    properties:
        email:
            - NotBlank:
                groups: [recover_password]
            - Regex:
                groups: [recover_password]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/
                message: "The email is not valid."

ReinventSoftware\UebusaitoBundle\Form\Model\CreditsModel:
    properties:
        credits:
            - NotBlank:
                groups: [profile_credits]
            - Regex:
                groups: [profile_credits]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The credits is not valid."

ReinventSoftware\UebusaitoBundle\Form\Model\LanguageModel:
    properties:
        codeText:
            - NotBlank:
                groups: [language_text]
            - Regex:
                groups: [language_text]
                htmlPattern: false
                pattern: /^[a-z]{2}$/
                message: "The code text is not valid."
        codePage:
            - NotBlank:
                groups: [language_code]
            - Regex:
                groups: [language_code]
                htmlPattern: false
                pattern: /^[a-z]{2}$/
                message: "The code page is not valid."

ReinventSoftware\UebusaitoBundle\Form\Model\SearchModel:
    properties:
        words:
            - NotBlank:
                groups: [search]

ReinventSoftware\UebusaitoBundle\Form\Model\PaymentsUserSelectionModel:
    properties:
        userId:
            - Regex:
                groups: [payments_user_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The user id is not valid."

ReinventSoftware\UebusaitoBundle\Form\Model\PaymentsSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [payments_selection]
            - Regex:
                groups: [payments_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The id is not valid."

ReinventSoftware\UebusaitoBundle\Form\Model\PagesSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [pages_selection]
            - Regex:
                groups: [pages_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The id is not valid."

ReinventSoftware\UebusaitoBundle\Form\Model\UsersSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [users_selection]
            - Regex:
                groups: [users_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The id is not valid."

ReinventSoftware\UebusaitoBundle\Form\Model\ModulesSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [modules_selection]
            - Regex:
                groups: [modules_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The id is not valid."

ReinventSoftware\UebusaitoBundle\Form\Model\RolesSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [roles_selection]
            - Regex:
                groups: [roles_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The id is not valid."

ReinventSoftware\UebusaitoBundle\Entity\Page:
    properties:
        language:
            - NotBlank:
                groups: [page_profile]
            - Regex:
                groups: [page_profile]
                htmlPattern: false
                pattern: /^[a-z]+$/
                message: "The language is not valid."
        parent:
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The parent is not valid."
        title:
            - NotBlank:
                groups: [page_creation, page_profile]
        roleId:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
                message: "The role is not valid."
        protected:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^1|^0/
                message: "The protected is not valid."
        showInMenu:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^1|^0/
                message: "The show in menu is not valid."
        menuName:
            - NotBlank:
                groups: [page_creation, page_profile]
        onlyLink:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^1|^0/
                message: "The menu link is not valid."
        link:
            - NotBlank:
                groups: [page_creation, page_profile]

ReinventSoftware\UebusaitoBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                groups: [registration, user_creation, user_profile]
            - Regex:
                groups: [registration, user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z0-9._]{4,20}$/
                message: "The username need min 4 max 20 character (Only . is allowed)."
        roleId:
            - NotBlank:
                groups: [user_creation, user_profile]
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
                message: "The role is not valid."
        name:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
                message: "The name is not valid."
        surname:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z']+$/
                message: "The surname is not valid."
        email:
            - NotBlank:
                groups: [registration, profile, user_creation, user_profile]
            - Regex:
                groups: [registration, profile, user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/
                message: "The email is not valid."
        telephone:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The telephone is not valid."
        born:
            - Date: ~
        gender:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]$/
                message: "The gender is not valid."
        fiscalCode:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z][0-9]$/
                message: "The fiscal code is not valid."
        companyName:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
                message: "The company name is not valid."
        companyCode:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The company code is not valid."
        website:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^(https?:\/\/)(www).([a-z0-9]+).([a-z]+)$/
                message: "The website is not valid."
        state:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
                message: "The state is not valid."
        city:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
                message: "The city is not valid."
        zip:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The zip is not valid."
        address:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z .0-9]+$/
                message: "The address is not valid."
        password:
            - NotBlank:
                groups: [registration, user_creation]
        passwordConfirm:
            - NotBlank:
                groups: [registration, user_creation]
        notLocked:
            - NotBlank:
                groups: [user_profile]
            - Regex:
                groups: [user_profile]
                htmlPattern: false
                pattern: /^1|^0/
                message: "The not locked is not valid."

ReinventSoftware\UebusaitoBundle\Entity\Module:
    properties:
        position:
            - NotBlank:
                groups: [module_creation]
            - Regex:
                groups: [module_creation, module_profile]
                htmlPattern: false
                pattern: /(header)|(left)|(center)|(right)/
                message: "The position is not valid."
        sort:
            - Regex:
                groups: [module_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
                message: "The sort is not valid."
        name:
            - NotBlank:
                groups: [module_creation, module_profile]
        fileName:
            - NotBlank:
                groups: [module_creation, module_profile]
            - Regex:
                groups: [module_creation, module_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z_.]+$/
                message: "The file name is not valid."
        active:
            - NotBlank:
                groups: [module_profile]
            - Regex:
                groups: [module_profile]
                htmlPattern: false
                pattern: /^1|^0/
                message: "The active is not valid."

ReinventSoftware\UebusaitoBundle\Entity\Role:
    properties:
        level:
            - NotBlank:
                groups: [role_creation, role_profile]
            - Regex:
                groups: [role_creation, role_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z_]+$/
                message: "The level is not valid."

ReinventSoftware\UebusaitoBundle\Entity\Setting:
    properties:
        template:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[a-zA-Z_0-9]+$/
                message: "The template is not valid."
        active:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^1|^0/
                message: "The active is not valid."
        https:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^1|^0/
                message: "The https is not valid."
        payPalBusiness:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/
                message: "The PayPal business is not valid."
        payPalCurrencyCode:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[A-Z]{3}$/
                message: "The PayPal currency code is not valid."
        payPalCreditAmount:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[0-9]+(\.[0-9][0-9]?)?$/
                message: "The PayPal credit amount is not valid."
        credits:
            - NotBlank:
                groups: [settings]
            - Regex:
                groups: [settings]
                htmlPattern: false
                pattern: /^[0-9]+$/
                message: "The Credit is not valid."