App\Form\Model\SearchModel:
    properties:
        words:
            - NotBlank:
                groups: [search_module]
            - Regex:
                groups: [search_module]
                htmlPattern: false
                pattern: /^.{1,150}$/

App\Form\Model\LanguageModel:
    properties:
        codePage:
            - NotBlank:
                groups: [language_code]
            - Regex:
                groups: [language_code]
                htmlPattern: false
                pattern: /^[a-z]{2}$/

App\Form\Model\RecoverPasswordModel:
    properties:
        email:
            - NotBlank:
                groups: [recover_password]
            - Regex:
                groups: [recover_password]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/

App\Form\Model\ChangePasswordModel:
    properties:
        password:
            - NotBlank:
                groups: [change_password]
            - Regex:
                groups: [change_password]
                htmlPattern: false
                pattern: /^.{8,30}$/
                message: entity.user.password
        passwordConfirm:
            - NotBlank:
                groups: [change_password]
            - Regex:
                groups: [change_password]
                htmlPattern: false
                pattern: /^.{8,30}$/
                message: entity.user.password

App\Form\Model\PasswordModel:
    properties:
        old:
            - NotBlank:
                groups: [profile_password]
            - Regex:
                groups: [profile_password]
                htmlPattern: false
                pattern: /^.{8,30}$/
                message: entity.user.password
        new:
            - NotBlank:
                groups: [profile_password]
            - Regex:
                groups: [profile_password]
                htmlPattern: false
                pattern: /^.{8,30}$/
                message: entity.user.password
        newConfirm:
            - NotBlank:
                groups: [profile_password]
            - Regex:
                groups: [profile_password]
                htmlPattern: false
                pattern: /^.{8,30}$/
                message: entity.user.password

App\Form\Model\CreditModel:
    properties:
        credit:
            - NotBlank:
                groups: [profile_credit]
            - Regex:
                groups: [profile_credit]
                htmlPattern: false
                pattern: /^[0-9]+$/

App\Form\Model\PaymentUserSelectionModel:
    properties:
        userId:
            - Regex:
                groups: [payment_user_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

App\Form\Model\PaymentSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [payment_selection]
            - Regex:
                groups: [payment_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

App\Form\Model\PageSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [page_selection]
            - Regex:
                groups: [page_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

App\Form\Model\UserSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [user_selection]
            - Regex:
                groups: [user_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

App\Form\Model\ModuleSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [module_selection]
            - Regex:
                groups: [module_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

App\Form\Model\ModuleDragModel:
    properties:
        positionLeft:
            - Regex:
                groups: [module_drag]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        positionCenter:
            - Regex:
                groups: [module_drag]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        positionRight:
            - Regex:
                groups: [module_drag]
                htmlPattern: false
                pattern: /^[0-9,]+$/

App\Form\Model\RoleUserSelectionModel:
    properties:
        id:
            - NotBlank:
                groups: [roleUser_selection]
            - Regex:
                groups: [roleUser_selection]
                htmlPattern: false
                pattern: /^[0-9]+$/

App\Entity\Page:
    properties:
        language:
            - NotBlank:
                groups: [page_profile]
            - Regex:
                groups: [page_profile]
                htmlPattern: false
                pattern: /^[a-z]+$/
        alias:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z_0-9]+$/
        parent:
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
        roleUserId:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        protected:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^1|^0/
        showInMenu:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^1|^0/
        rankMenuSort:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        menuName:
            - NotBlank:
                groups: [page_creation, page_profile]
        onlyLink:
            - NotBlank:
                groups: [page_creation, page_profile]
            - Regex:
                groups: [page_creation, page_profile]
                htmlPattern: false
                pattern: /^1|^0/
        link:
            - NotBlank:
                groups: [page_creation, page_profile]

App\Entity\PageComment:
    properties:
        argument:
            - NotBlank:
                groups: [pageComment]
            - Regex:
                groups: [pageComment]
                htmlPattern: false
                pattern: /^.{1,255}$/

App\Entity\User:
    properties:
        roleUserId:
            - NotBlank:
                groups: [user_creation, user_profile]
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        username:
            - NotBlank:
                groups: [registration, user_creation, user_profile]
            - Regex:
                groups: [registration, user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z0-9._]{4,20}$/
                message: entity.user.username
        name:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
        surname:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z']+$/
        email:
            - NotBlank:
                groups: [registration, profile, user_creation, user_profile]
            - Regex:
                groups: [registration, profile, user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/
        telephone:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
        born:
            - Regex:
                groups: [registration, profile, user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]{4}-[0-9]{1,2}-[0-9]{1,2}|[0-9]{1,2}-[0-9]{1,2}-[0-9]{4}|[0-9]{4}\/[0-9]{1,2}\/[0-9]{1,2}|[0-9]{1,2}\/[0-9]{1,2}\/[0-9]{4}$/
        gender:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]$/
        fiscalCode:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z][0-9]$/
        companyName:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
        vat:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
        website:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^(https?:\/\/)(www).([a-z0-9]+).([a-z]+)$/
        state:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
        city:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z]+$/
        zip:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
        address:
            - Regex:
                groups: [user_creation, user_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z .0-9]+$/
        password:
            - NotBlank:
                groups: [registration, user_creation]
            - Regex:
                groups: [registration, user_creation]
                htmlPattern: false
                pattern: /^.{8,30}$/
                message: entity.user.password
        passwordConfirm:
            - NotBlank:
                groups: [registration, user_creation]
            - Regex:
                groups: [registration, user_creation]
                htmlPattern: false
                pattern: /^.{8,30}$/
                message: entity.user.password
        notLocked:
            - NotBlank:
                groups: [user_profile]
            - Regex:
                groups: [user_profile]
                htmlPattern: false
                pattern: /^1|^0/

App\Entity\Module:
    properties:
        position:
            - NotBlank:
                groups: [module_creation, module_profile]
            - Regex:
                groups: [module_creation, module_profile]
                htmlPattern: false
                pattern: /(header)|(left)|(center)|(right)/
        rankInColumn:
            - Regex:
                groups: [module_creation, module_profile]
                htmlPattern: false
                pattern: /^[0-9]+$/
        rankColumnSort:
            - NotBlank:
                groups: [module_creation, module_profile]
            - Regex:
                groups: [module_creation, module_profile]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        name:
            - NotBlank:
                groups: [module_creation, module_profile]
        controllerName:
            - NotBlank:
                groups: [module_creation, module_profile]
            - Regex:
                groups: [module_creation, module_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z::]+$/
        active:
            - NotBlank:
                groups: [module_profile]
            - Regex:
                groups: [module_profile]
                htmlPattern: false
                pattern: /^1|^0/

App\Entity\RoleUser:
    properties:
        level:
            - NotBlank:
                groups: [roleUser_creation, roleUser_profile]
            - Regex:
                groups: [roleUser_creation, roleUser_profile]
                htmlPattern: false
                pattern: /^[a-zA-Z_]+$/

App\Entity\Setting:
    properties:
        template:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[a-zA-Z_0-9]+$/
        templateColumn:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[1-4]+$/
        language:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[a-z]{2}$/
        pageDate:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^1|^0/
        pageComment:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^1|^0/
        pageCommentActive:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^1|^0/
        emailAdmin:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/
        websiteActive:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^1|^0/
        roleUserId:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[0-9,]+$/
        https:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^1|^0/
        registrationUserConfirmAdmin:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^1|^0/
        loginAttemptTime:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[0-9]+$/
        loginAttemptCount:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[0-9]+$/
        captcha:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^1|^0/
        payPalSandbox:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^1|^0/
        payPalBusiness:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[a-z0-9]+[_a-z0-9\.-]*[a-z0-9]+@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,5})$/
        payPalCurrencyCode:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[A-Z]{3}$/
        payPalCreditAmount:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[0-9]+(\.[0-9][0-9]?)?$/
        credit:
            - NotBlank:
                groups: [setting]
            - Regex:
                groups: [setting]
                htmlPattern: false
                pattern: /^[0-9]+$/